# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(841, 725)
        self.tab_metrics = QtWidgets.QTabWidget(Dialog)
        self.tab_metrics.setGeometry(QtCore.QRect(10, 330, 761, 311))
        self.tab_metrics.setObjectName("tab_metrics")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 220, 131, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lbl_groundtruth_dir_5 = QtWidgets.QLabel(self.tab)
        self.lbl_groundtruth_dir_5.setGeometry(QtCore.QRect(40, 220, 221, 17))
        self.lbl_groundtruth_dir_5.setObjectName("lbl_groundtruth_dir_5")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 371, 101))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 70, 351, 22))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 40, 351, 22))
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.lbl_detections_dir_6 = QtWidgets.QLabel(self.frame_5)
        self.lbl_detections_dir_6.setGeometry(QtCore.QRect(10, 10, 181, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detections_dir_6.setFont(font)
        self.lbl_detections_dir_6.setObjectName("lbl_detections_dir_6")
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setGeometry(QtCore.QRect(20, 120, 371, 101))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lbl_detections_dir_9 = QtWidgets.QLabel(self.frame_7)
        self.lbl_detections_dir_9.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.lbl_detections_dir_9.setObjectName("lbl_detections_dir_9")
        self.tab_metrics.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 351, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.lbl_groundtruth_dir_6 = QtWidgets.QLabel(self.frame_8)
        self.lbl_groundtruth_dir_6.setGeometry(QtCore.QRect(10, 100, 221, 17))
        self.lbl_groundtruth_dir_6.setObjectName("lbl_groundtruth_dir_6")
        self.lbl_groundtruth_dir_7 = QtWidgets.QLabel(self.frame_8)
        self.lbl_groundtruth_dir_7.setGeometry(QtCore.QRect(10, 70, 221, 17))
        self.lbl_groundtruth_dir_7.setObjectName("lbl_groundtruth_dir_7")
        self.lbl_groundtruth_dir_8 = QtWidgets.QLabel(self.frame_8)
        self.lbl_groundtruth_dir_8.setGeometry(QtCore.QRect(10, 40, 131, 17))
        self.lbl_groundtruth_dir_8.setObjectName("lbl_groundtruth_dir_8")
        self.lbl_groundtruth_dir_18 = QtWidgets.QLabel(self.frame_8)
        self.lbl_groundtruth_dir_18.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_groundtruth_dir_18.setFont(font)
        self.lbl_groundtruth_dir_18.setObjectName("lbl_groundtruth_dir_18")
        self.frame_9 = QtWidgets.QFrame(self.tab_2)
        self.frame_9.setGeometry(QtCore.QRect(370, 10, 381, 121))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lbl_groundtruth_dir_9 = QtWidgets.QLabel(self.frame_9)
        self.lbl_groundtruth_dir_9.setGeometry(QtCore.QRect(10, 40, 221, 17))
        self.lbl_groundtruth_dir_9.setObjectName("lbl_groundtruth_dir_9")
        self.lbl_groundtruth_dir_11 = QtWidgets.QLabel(self.frame_9)
        self.lbl_groundtruth_dir_11.setGeometry(QtCore.QRect(10, 100, 221, 17))
        self.lbl_groundtruth_dir_11.setObjectName("lbl_groundtruth_dir_11")
        self.lbl_groundtruth_dir_10 = QtWidgets.QLabel(self.frame_9)
        self.lbl_groundtruth_dir_10.setGeometry(QtCore.QRect(10, 70, 221, 17))
        self.lbl_groundtruth_dir_10.setObjectName("lbl_groundtruth_dir_10")
        self.lbl_groundtruth_dir_20 = QtWidgets.QLabel(self.frame_9)
        self.lbl_groundtruth_dir_20.setGeometry(QtCore.QRect(10, 10, 221, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_groundtruth_dir_20.setFont(font)
        self.lbl_groundtruth_dir_20.setObjectName("lbl_groundtruth_dir_20")
        self.frame_10 = QtWidgets.QFrame(self.tab_2)
        self.frame_10.setGeometry(QtCore.QRect(370, 140, 381, 131))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.lbl_groundtruth_dir_13 = QtWidgets.QLabel(self.frame_10)
        self.lbl_groundtruth_dir_13.setGeometry(QtCore.QRect(10, 100, 221, 17))
        self.lbl_groundtruth_dir_13.setObjectName("lbl_groundtruth_dir_13")
        self.lbl_groundtruth_dir_14 = QtWidgets.QLabel(self.frame_10)
        self.lbl_groundtruth_dir_14.setGeometry(QtCore.QRect(10, 40, 221, 17))
        self.lbl_groundtruth_dir_14.setObjectName("lbl_groundtruth_dir_14")
        self.lbl_groundtruth_dir_12 = QtWidgets.QLabel(self.frame_10)
        self.lbl_groundtruth_dir_12.setGeometry(QtCore.QRect(10, 70, 221, 17))
        self.lbl_groundtruth_dir_12.setObjectName("lbl_groundtruth_dir_12")
        self.lbl_groundtruth_dir_21 = QtWidgets.QLabel(self.frame_10)
        self.lbl_groundtruth_dir_21.setGeometry(QtCore.QRect(10, 10, 221, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_groundtruth_dir_21.setFont(font)
        self.lbl_groundtruth_dir_21.setObjectName("lbl_groundtruth_dir_21")
        self.frame_11 = QtWidgets.QFrame(self.tab_2)
        self.frame_11.setGeometry(QtCore.QRect(10, 140, 351, 131))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.lbl_groundtruth_dir_15 = QtWidgets.QLabel(self.frame_11)
        self.lbl_groundtruth_dir_15.setGeometry(QtCore.QRect(10, 100, 221, 17))
        self.lbl_groundtruth_dir_15.setObjectName("lbl_groundtruth_dir_15")
        self.lbl_groundtruth_dir_16 = QtWidgets.QLabel(self.frame_11)
        self.lbl_groundtruth_dir_16.setGeometry(QtCore.QRect(10, 40, 221, 17))
        self.lbl_groundtruth_dir_16.setObjectName("lbl_groundtruth_dir_16")
        self.lbl_groundtruth_dir_17 = QtWidgets.QLabel(self.frame_11)
        self.lbl_groundtruth_dir_17.setGeometry(QtCore.QRect(10, 70, 221, 17))
        self.lbl_groundtruth_dir_17.setObjectName("lbl_groundtruth_dir_17")
        self.lbl_groundtruth_dir_19 = QtWidgets.QLabel(self.frame_11)
        self.lbl_groundtruth_dir_19.setGeometry(QtCore.QRect(10, 10, 221, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_groundtruth_dir_19.setFont(font)
        self.lbl_groundtruth_dir_19.setObjectName("lbl_groundtruth_dir_19")
        self.tab_metrics.addTab(self.tab_2, "")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 761, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lbl_groundtruth_dir = QtWidgets.QLabel(self.tab_3)
        self.lbl_groundtruth_dir.setGeometry(QtCore.QRect(10, 45, 101, 17))
        self.lbl_groundtruth_dir.setObjectName("lbl_groundtruth_dir")
        self.btn_gt_dir = QtWidgets.QPushButton(self.tab_3)
        self.btn_gt_dir.setGeometry(QtCore.QRect(720, 40, 31, 27))
        self.btn_gt_dir.setObjectName("btn_gt_dir")
        self.txb_gt_dir = QtWidgets.QLineEdit(self.tab_3)
        self.txb_gt_dir.setGeometry(QtCore.QRect(110, 40, 601, 27))
        self.txb_gt_dir.setReadOnly(True)
        self.txb_gt_dir.setObjectName("txb_gt_dir")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(390, 100, 361, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.rad_gt_type_absolute = QtWidgets.QRadioButton(self.frame_2)
        self.rad_gt_type_absolute.setGeometry(QtCore.QRect(20, 40, 181, 22))
        self.rad_gt_type_absolute.setChecked(True)
        self.rad_gt_type_absolute.setObjectName("rad_gt_type_absolute")
        self.lbl_detections_dir_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_detections_dir_2.setGeometry(QtCore.QRect(20, 10, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detections_dir_2.setFont(font)
        self.lbl_detections_dir_2.setObjectName("lbl_detections_dir_2")
        self.rad_gt_type_relative = QtWidgets.QRadioButton(self.frame_2)
        self.rad_gt_type_relative.setGeometry(QtCore.QRect(20, 70, 181, 22))
        self.rad_gt_type_relative.setObjectName("rad_gt_type_relative")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(10, 100, 371, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.rad_gt_format_xywh = QtWidgets.QRadioButton(self.frame)
        self.rad_gt_format_xywh.setGeometry(QtCore.QRect(10, 70, 351, 22))
        self.rad_gt_format_xywh.setObjectName("rad_gt_format_xywh")
        self.rad_gt_format_xyx2y2 = QtWidgets.QRadioButton(self.frame)
        self.rad_gt_format_xyx2y2.setGeometry(QtCore.QRect(10, 40, 351, 22))
        self.rad_gt_format_xyx2y2.setChecked(True)
        self.rad_gt_format_xyx2y2.setObjectName("rad_gt_format_xyx2y2")
        self.lbl_detections_dir_3 = QtWidgets.QLabel(self.frame)
        self.lbl_detections_dir_3.setGeometry(QtCore.QRect(10, 10, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detections_dir_3.setFont(font)
        self.lbl_detections_dir_3.setObjectName("lbl_detections_dir_3")
        self.rad_gt_format_pascal = QtWidgets.QRadioButton(self.frame)
        self.rad_gt_format_pascal.setGeometry(QtCore.QRect(10, 100, 351, 22))
        self.rad_gt_format_pascal.setObjectName("rad_gt_format_pascal")
        self.btn_gt_images_dir = QtWidgets.QPushButton(self.tab_3)
        self.btn_gt_images_dir.setGeometry(QtCore.QRect(720, 70, 31, 27))
        self.btn_gt_images_dir.setObjectName("btn_gt_images_dir")
        self.txb_gt_images_dir = QtWidgets.QLineEdit(self.tab_3)
        self.txb_gt_images_dir.setGeometry(QtCore.QRect(110, 70, 601, 27))
        self.txb_gt_images_dir.setReadOnly(True)
        self.txb_gt_images_dir.setObjectName("txb_gt_images_dir")
        self.lbl_groundtruth_dir_2 = QtWidgets.QLabel(self.tab_3)
        self.lbl_groundtruth_dir_2.setGeometry(QtCore.QRect(10, 75, 101, 17))
        self.lbl_groundtruth_dir_2.setObjectName("lbl_groundtruth_dir_2")
        self.btn_stats_gt = QtWidgets.QPushButton(self.tab_3)
        self.btn_stats_gt.setGeometry(QtCore.QRect(10, 240, 741, 27))
        self.btn_stats_gt.setObjectName("btn_stats_gt")
        self.lbl_groundtruth_dir_3 = QtWidgets.QLabel(self.tab_3)
        self.lbl_groundtruth_dir_3.setGeometry(QtCore.QRect(10, 10, 731, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_groundtruth_dir_3.setFont(font)
        self.lbl_groundtruth_dir_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_groundtruth_dir_3.setObjectName("lbl_groundtruth_dir_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.btn_groundtruth_dir_3 = QtWidgets.QPushButton(self.tab_4)
        self.btn_groundtruth_dir_3.setGeometry(QtCore.QRect(720, 40, 31, 27))
        self.btn_groundtruth_dir_3.setObjectName("btn_groundtruth_dir_3")
        self.txb_det_dir = QtWidgets.QLineEdit(self.tab_4)
        self.txb_det_dir.setGeometry(QtCore.QRect(110, 40, 601, 27))
        self.txb_det_dir.setReadOnly(True)
        self.txb_det_dir.setObjectName("txb_det_dir")
        self.lbl_groundtruth_dir_4 = QtWidgets.QLabel(self.tab_4)
        self.lbl_groundtruth_dir_4.setGeometry(QtCore.QRect(10, 45, 101, 17))
        self.lbl_groundtruth_dir_4.setObjectName("lbl_groundtruth_dir_4")
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(390, 80, 361, 101))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.rad_det_type_absolute = QtWidgets.QRadioButton(self.frame_3)
        self.rad_det_type_absolute.setGeometry(QtCore.QRect(20, 40, 181, 22))
        self.rad_det_type_absolute.setChecked(True)
        self.rad_det_type_absolute.setObjectName("rad_det_type_absolute")
        self.lbl_detections_dir_4 = QtWidgets.QLabel(self.frame_3)
        self.lbl_detections_dir_4.setGeometry(QtCore.QRect(20, 10, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detections_dir_4.setFont(font)
        self.lbl_detections_dir_4.setObjectName("lbl_detections_dir_4")
        self.rad_det_type_relative = QtWidgets.QRadioButton(self.frame_3)
        self.rad_det_type_relative.setGeometry(QtCore.QRect(20, 70, 181, 22))
        self.rad_det_type_relative.setObjectName("rad_det_type_relative")
        self.frame_4 = QtWidgets.QFrame(self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(10, 80, 371, 131))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.rad_det_format_xywh = QtWidgets.QRadioButton(self.frame_4)
        self.rad_det_format_xywh.setGeometry(QtCore.QRect(10, 70, 351, 22))
        self.rad_det_format_xywh.setObjectName("rad_det_format_xywh")
        self.rad_det_format_xyx2y2 = QtWidgets.QRadioButton(self.frame_4)
        self.rad_det_format_xyx2y2.setGeometry(QtCore.QRect(10, 40, 351, 22))
        self.rad_det_format_xyx2y2.setChecked(True)
        self.rad_det_format_xyx2y2.setObjectName("rad_det_format_xyx2y2")
        self.lbl_detections_dir_5 = QtWidgets.QLabel(self.frame_4)
        self.lbl_detections_dir_5.setGeometry(QtCore.QRect(10, 10, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detections_dir_5.setFont(font)
        self.lbl_detections_dir_5.setObjectName("lbl_detections_dir_5")
        self.rad_det_format_pascal = QtWidgets.QRadioButton(self.frame_4)
        self.rad_det_format_pascal.setGeometry(QtCore.QRect(10, 100, 351, 22))
        self.rad_det_format_pascal.setObjectName("rad_det_format_pascal")
        self.btn_stats_det = QtWidgets.QPushButton(self.tab_4)
        self.btn_stats_det.setGeometry(QtCore.QRect(10, 220, 741, 27))
        self.btn_stats_det.setObjectName("btn_stats_det")
        self.lbl_groundtruth_dir_22 = QtWidgets.QLabel(self.tab_4)
        self.lbl_groundtruth_dir_22.setGeometry(QtCore.QRect(10, 10, 731, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_groundtruth_dir_22.setFont(font)
        self.lbl_groundtruth_dir_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_groundtruth_dir_22.setObjectName("lbl_groundtruth_dir_22")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tab_metrics.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.btn_gt_dir.clicked.connect(Dialog.btn_gt_dir_clicked)
        self.btn_gt_images_dir.clicked.connect(Dialog.btn_gt_images_dir_clicked)
        self.btn_groundtruth_dir_3.clicked.connect(Dialog.btn_det_dir_clicked)
        self.btn_stats_gt.clicked.connect(Dialog.btn_statistics_gt_clicked)
        self.btn_stats_det.clicked.connect(Dialog.btn_statistics_det_clicked)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Object Detection Metrics"))
        self.pushButton_3.setToolTip(_translate("Dialog", "The configurations will be applied in a random ground truth image."))
        self.pushButton_3.setText(_translate("Dialog", "mAP"))
        self.lbl_groundtruth_dir_5.setText(_translate("Dialog", "Mean Average Precision (mAP):"))
        self.radioButton_9.setText(_translate("Dialog", "All points interpolation"))
        self.radioButton_10.setText(_translate("Dialog", "11-point interpolation"))
        self.lbl_detections_dir_6.setText(_translate("Dialog", "Interpolation method:"))
        self.lbl_detections_dir_9.setText(_translate("Dialog", "IOU threshold:"))
        self.tab_metrics.setTabText(self.tab_metrics.indexOf(self.tab), _translate("Dialog", "PASCAL VOC"))
        self.lbl_groundtruth_dir_6.setText(_translate("Dialog", "AP@50:"))
        self.lbl_groundtruth_dir_7.setText(_translate("Dialog", "AP@75:"))
        self.lbl_groundtruth_dir_8.setText(_translate("Dialog", "AP@[.50: .05: .95]"))
        self.lbl_groundtruth_dir_18.setText(_translate("Dialog", "Average Precision (AP):"))
        self.lbl_groundtruth_dir_9.setText(_translate("Dialog", "AP small:"))
        self.lbl_groundtruth_dir_11.setText(_translate("Dialog", "AP large:"))
        self.lbl_groundtruth_dir_10.setText(_translate("Dialog", "AP medium:"))
        self.lbl_groundtruth_dir_20.setText(_translate("Dialog", "AP Across Scales:"))
        self.lbl_groundtruth_dir_13.setText(_translate("Dialog", "AR large:"))
        self.lbl_groundtruth_dir_14.setText(_translate("Dialog", "AR small:"))
        self.lbl_groundtruth_dir_12.setText(_translate("Dialog", "AR medium:"))
        self.lbl_groundtruth_dir_21.setText(_translate("Dialog", "AR Across Scales:"))
        self.lbl_groundtruth_dir_15.setText(_translate("Dialog", "AR max=100:"))
        self.lbl_groundtruth_dir_16.setText(_translate("Dialog", "AR max=1:"))
        self.lbl_groundtruth_dir_17.setText(_translate("Dialog", "AR max=10:"))
        self.lbl_groundtruth_dir_19.setText(_translate("Dialog", "Average Recall (AR):"))
        self.tab_metrics.setTabText(self.tab_metrics.indexOf(self.tab_2), _translate("Dialog", "COCO"))
        self.lbl_groundtruth_dir.setText(_translate("Dialog", "Annotations:"))
        self.btn_gt_dir.setText(_translate("Dialog", "..."))
        self.rad_gt_type_absolute.setText(_translate("Dialog", "absolute"))
        self.lbl_detections_dir_2.setText(_translate("Dialog", "Coordinates values:"))
        self.rad_gt_type_relative.setText(_translate("Dialog", "relative"))
        self.rad_gt_format_xywh.setText(_translate("Dialog", "<class_name> <left> <top> <width> <height>"))
        self.rad_gt_format_xyx2y2.setText(_translate("Dialog", "<class_name> <left> <top> <right> <bottom>"))
        self.lbl_detections_dir_3.setText(_translate("Dialog", "Coordinates format:"))
        self.rad_gt_format_pascal.setToolTip(_translate("Dialog", "<html><head/><body><p>Ground-truth format provided by PASCAL VOC annotated files (.XML).</p><p>Reference:</p><p><a href=\"http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/devkit_doc.html#SECTION00035000000000000000\"><span style=\" text-decoration: underline; color:#0000ff;\">http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/devkit_doc.html#SECTION00035000000000000000</span></a>"))
        self.rad_gt_format_pascal.setText(_translate("Dialog", "PASCAL VOC format (XML)"))
        self.btn_gt_images_dir.setText(_translate("Dialog", "..."))
        self.lbl_groundtruth_dir_2.setText(_translate("Dialog", "Images:"))
        self.btn_stats_gt.setToolTip(_translate("Dialog", "The configurations will be applied in a random ground truth image."))
        self.btn_stats_gt.setText(_translate("Dialog", "view ground-truth statistics"))
        self.lbl_groundtruth_dir_3.setText(_translate("Dialog", "Ground truth"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Ground truth"))
        self.btn_groundtruth_dir_3.setText(_translate("Dialog", "..."))
        self.lbl_groundtruth_dir_4.setText(_translate("Dialog", "Annotations:"))
        self.rad_det_type_absolute.setText(_translate("Dialog", "absolute"))
        self.lbl_detections_dir_4.setText(_translate("Dialog", "Coordinates values:"))
        self.rad_det_type_relative.setText(_translate("Dialog", "relative"))
        self.rad_det_format_xywh.setText(_translate("Dialog", "<class_name> <left> <top> <width> <height>"))
        self.rad_det_format_xyx2y2.setText(_translate("Dialog", "<class_name> <left> <top> <right> <bottom>"))
        self.lbl_detections_dir_5.setText(_translate("Dialog", "Coordinates format:"))
        self.rad_det_format_pascal.setToolTip(_translate("Dialog", "<html><head/><body><p>Request format by PASCAL VOC competition to submit results:</p><p><span style=\" font-weight:600;\">&lt;image identifier&gt; &lt;confidence&gt; &lt;left&gt; &lt;top&gt; &lt;right&gt; &lt;bottom&gt;</span></p><p>Reference: <a href=\"http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/devkit_doc.html#SECTION00053000000000000000\"><span style=\" text-decoration: underline; color:#0000ff;\">http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/devkit_doc.html#SECTION00053000000000000000</span></a></p></body></html>"))
        self.rad_det_format_pascal.setText(_translate("Dialog", "PASCAL VOC (submission results)"))
        self.btn_stats_det.setToolTip(_translate("Dialog", "The configurations will be applied in a random ground truth image."))
        self.btn_stats_det.setText(_translate("Dialog", "view detections statistics"))
        self.lbl_groundtruth_dir_22.setText(_translate("Dialog", "Detections"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Detections"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

